//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppPerfume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART
    {
        public int CARTID { get; set; }
        public Nullable<int> idUSER { get; set; }
        public Nullable<int> idPROD { get; set; }
        public string NAME { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string PIC { get; set; }
        public Nullable<int> QTY { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
