//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppPerfume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int ODID { get; set; }
        public Nullable<int> orderID { get; set; }
        public string proName { get; set; }
        public Nullable<double> proPrice { get; set; }
        public string proPIC { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> proID { get; set; }
    
        public virtual ORDER ORDER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
